<a href="https://colab.research.google.com/github/aman65823/amanproject-demo/blob/main/Intronumpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

a = np.array([2, 4, 44, 244])
b = np.array([4, 34, 35, 521])
add_ans = a + b
print(add_ans)
#arithmetic operation

[  6  38  79 765]


In [3]:
print(np.add(a, b))
#function of numpy using numpy

[  6  38  79 765]


In [ ]:
#mean medain and standard deviation

In [5]:
array = np.arange(10)
print(array)
r1 = np.mean(array)
print("/mean: ", r1)

[0 1 2 3 4 5 6 7 8 9]
/mean:  4.5


In [7]:
r2 = np.std(array)
print("/std: ", r2)

r3 = np.var(array)
print("/nvar: ", r3)

/std:  2.8722813232690143
/nvar:  8.25


In [8]:
#convert one shape to another shape


In [13]:
import numpy as np
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16])
print("Array : " + str(array))
n= array.size
N = 4
M = n//4
reshaped1 = array.reshape((N, M))

print(" firet reshaped1 array : " )
print(reshaped1)
reshaped2 = np.reshape(array,(2,8))
print("Second Reshaped Array : ")
print(reshaped2)

Array : [0 1 2 3 4 5 6 7 8 9]


ValueError: cannot reshape array of size 10 into shape (4,2)

In [14]:
# importing numpy
import numpy as np

# creating a numpy array
array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16])

# printing array
print("Array : " + str(array))

# length of array
n = array.size

# N-D array N dimension
N = 4

# calculating M
M = n//N

# reshaping numpy array
# converting it to 2-D from 1-D array
reshaped1 = array.reshape((N, M))

# printing reshaped array
print("First Reshaped Array : ")
print(reshaped1)

# creating another reshaped array
reshaped2 = np.reshape(array, (2, 8))

# printing reshaped array
print("Second Reshaped Array : ")
print(reshaped2)


Array : [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
First Reshaped Array : 
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Second Reshaped Array : 
[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]]
